name: Bug Report
description: "Report a bug or issue you've encountered."
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: >
        Provide a clear and concise description of the bug here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        You can get the application logs in one of two ways:

        1. **From the App:**
          Go to **About > Troubleshooting** to view or export logs.

        2. **From the Terminal:**
          Run the command below, then upload the generated `packet.log` file here (you can drag & drop or paste it).

        **For Flatpak:**

        ```
        flatpak run io.github.nozwock.Packet | tee packet.log
        ```

        **For Non-Flatpak:**

        ```
        export RUST_LOG=packet=debug,rqs_lib=debug
        packet | tee packet.log
        ```
      placeholder: |
        Paste your log output here or drag & drop the `packet.log` file into this box.
    validations:
      required: false

  - type: checkboxes
    id: flatpak
    attributes:
      label: Distribution Type
      description: Are you using the Flatpak version of Packet?
      options:
        - label: Yes, I'm using the Flatpak version
          required: false

  - type: textarea
    id: platform
    attributes:
      label: Platform Info
      description: >
        Enter details such as your Linux distribution's name and version, and other relevant info.
      placeholder: |
        Example:
        - Distro: Fedora 42
        - Installation Method: AUR
    validations:
      required: false
